name: Costruisci APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Controlla il codice
        uses: actions/checkout@v3

      - name: Configura Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Installa Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Installa pacchetti
        run: npm install

      - name: Crea la Build Android (APK)
        run: eas build -p android --profile preview --non-interactive