name: Costruisci APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Controlla il codice
        uses: actions/checkout@v4

      - name: Configura Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installa EAS (Il costruttore)
        run: npm install -g eas-cli

      - name: Installa pacchetti
        run: npm install

      - name: Crea la Build Android (APK)
        run: eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}