name: Costruisci APK (Zero Code)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Controlla il codice
        uses: actions/checkout@v4

      - name: Configura Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configura Java (Serve per Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Installa EAS
        run: npm install -g eas-cli

      - name: Installa pacchetti
        run: npm install

      - name: Crea APK saltando Expo
        run: eas build -p android --profile preview --local --output ./netchill.apk
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_NO_VCS: 1

      - name: Salva l'APK per il download
        uses: actions/upload-artifact@v4
        with:
          name: NetChill-App
          path: ./netchill.apk